version: '3'

services:
  docuwhisper-backend-service:
    container_name: docuwhisper-backend-service
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    restart: always
    depends_on:
      docuwhisper-postgres-service:
        condition: service_healthy
    networks:
      - docuwhisper_network

  docuwhisper-postgres-service:
    container_name: docuwhisper-postgres-service
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=docuwhisper
    volumes:
      - docuwhisper-postgres_data:/var/lib/postgresql/data/
    ports:
      - '5433:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - docuwhisper_network

networks:
  docuwhisper_network:
    name: docuwhisper_network
    external: true

volumes:
  docuwhisper-postgres_data:
    driver: local
    name: docuwhisper-postgres_data

